import type { Metadata } from "next";
// import localFont from "next/font/google";
import "./globals.css";
import ConditionalSideBar from "@/components/ConditionalSideBar";
import { Geist, Geist_Mono } from 'next/font/google'


// Use your font
const geist = Geist({
  weight: '400', // adjust as needed
  style: 'normal',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  weight: '400', // adjust as needed
  style: 'normal',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.style} ${geistMono.style} antialiased`}>
        {children}
        <ConditionalSideBar />
      </body>
    </html>
  );
}
