import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ConditionalSideBar from "@/components/ConditionalSideBar";


// Correct paths to font files in the public/fonts/ directory
const geistSans = localFont({
  src: "/fonts/GeistVF.woff",  // Correct font path
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff",  // Correct font path
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <ConditionalSideBar />
      </body>
    </html>
  );
}
